language: node_js
node_js:
  - node
deploy:
  provider: heroku
  app: lawn-mowers
  api_key:
    secure: T8cp7aEuO7Q7ljK6X4McEafeFGt+qDKbVSCPxN1K47G2cPqP5m+pB7YW3N2eebVhUuIXEUr/D3feVIr8G/Y9Aya4XEzngESFUlLim8LIAnv4xZTBSsPft5Cd4h4qrLE2Omz8IWKUK6O/qQH2zaWn+9G+d7uu++WUXuIKQxioY3HaockBPE/d1TLJDg9u8BBQmux+zFMxoWmb0gV59qD7XuizX5R4EkQZZecfLY4H9E1Gy2gG3Qdppdl6e3AB6MAA0j9jIvBFwfSn6PM+ZoSv+BUGnGHlRlYrJA4/wz7v6ewXCP0YchGv8QPiZfuKMCHXpu9iC2Y3zo8MKWVBmxBWQVVjpUh+impXUIH2n8k1LnqFfRsFhr7867MzoLbtRVoH9OwgaK7nIFxoLeLUPc9C+l/ovzDJVhhkhphtuOQP54DAyTdllIADfSUBIsC4LYKZxP7VVn9kyU4/ovLlIDdaMFTPMTLLVNiXF5vVhdBoUEroXyUMJijNadORtci1cdYd/KQSJAhzPJBY09NZ/cJL5RbdoFyv1g7ePabPKwA7/gC2Leh1/hfzBhzG+S782wsUes0g52JPFD08TYO2BqjQ58mPYE2apiGw4BZZZh7ERV3F/yguxoHDajJfeDekXPgu94MFhrm29hsskfR6cYypegFhpyvl9rpfJzgsWFBeFhU=
